apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
spec:
  replicas: 3
  template:
    metadata:
  name: nginx-pod1
  labels:
    teams: integerations
    app: todo
  spec: 
    containers: 
      - name: nginx-container
        image: nginx:latest
        ports:
          - containerPort: 80